### ISSUE TITLE
Compile and build  & flash process for fimrware

### ISSUE THREAD

**Issue by vaibhavkambli** [happy-bubbles/presence-firmware#12]
Hello,
Can u please provide any documented support or guide/Readme for happy bubble presence detector firmware building(make process) and installation process.
I need to do custom additions in firmware.
i already installed esp-open-sdk. How can i compile this project with help of those?
I tried simple make command which failed to work.Please support.

**Comment by nemik** [comment]
In the future, if a command you tried didn't work, it's best to say what didn't work. If you want help adding proprietary additions, I can do that for a fee. Please email business@happybubbles.tech
