### ISSUE TITLE
group_key_update_timeout

### ISSUE THREAD

**Issue by BrianAker** [happy-bubbles/presence-firmware#2]
With the latest firmware when I go to setup the WiFi I get a group_key_update_timeout error.

**Comment by nemik** [comment]
Sorry to hear you're having trouble with it, Brian. I have not encountered this error before. What kind of encryption is the wifi access point you're trying to connect to using? What if you try a different one?

**Comment by BrianAker** [comment]
WPA2-AES
MFP: capable

乌

**Comment by nemik** [comment]
Maybe it's the MFP that's causing it? What vendor makes your AP? I tested mine successfully on TP Link running wpa2 with openwrt and also ubiquiti ones, they both worked fine.
Sorry to say but you might need to adjust some AP settings if you're getting that error. I'm not sure if the ESP8266 chipset that the hardware is based on supports things like MFP.

**Comment by BrianAker** [comment]
The AP is Cisco and the previous firmware works.

Poking around I think this is an issue with one structure being reset properly when the device tries to connect to the AP.
