### ISSUE TITLE
Info about ble_module compilation

### ISSUE THREAD

**Issue by monster1025** [happy-bubbles/presence-firmware#3]
Hi.
Thank you for such great project.
I am trying to use your ble_module firmware, i have uploaded hex-file as-is in my PTR5518 and it works great, but i meed to make some changes in code. How I can build (compile) it? Which IDE and libraries\stack do you use? Maybe you have some scripts for building it?

Thank you for info =)

**Comment by nemik** [comment]
You're welcome. It was compiled using mbed: https://developer.mbed.org/compiler/

What changes are you looking to make? If they're useful, maybe would be nice to contribute them back to this project too :)
